version:  '3.3'

services: 
    db:
        image: mysql
        container_name: mysql
        restart: always
        ports: 
            - 3306:3306
        volumes: 
            - ./data/:/var/lib/mysql
        environment: 
            - DB_ROOT_PASSWORD: mysql