version:  '3.3'

services: 
    db:
        image: mysql
        container_name: mysql
        volumes: 
            - db_data/:/var/lib/mysql
        restart: always
        environment: 
            DB_ROOT_PASSWORD: mysql
        ports: 
            - '3306:3306'

    phpmyadmin:
        image: phpmyadmin
        container_name: myadmin
        restart: always
        ports: 
            - '8081:80'
        environment: 
            MYSQL_ROOT_PASSWORD: mysql